# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseBNF <- function(filepath, strict_mode = FALSE, preserve_whitespace = TRUE, allow_empty_rules = FALSE, detect_left_recursion = TRUE, allow_ebnf = TRUE, validate_references = TRUE) {
    .Call(`_bnfparser_parseBNF`, filepath, strict_mode, preserve_whitespace, allow_empty_rules, detect_left_recursion, allow_ebnf, validate_references)
}

parseBNFString <- function(grammar_string, strict_mode = FALSE, preserve_whitespace = TRUE, allow_empty_rules = FALSE, detect_left_recursion = TRUE, allow_ebnf = TRUE, validate_references = TRUE) {
    .Call(`_bnfparser_parseBNFString`, grammar_string, strict_mode, preserve_whitespace, allow_empty_rules, detect_left_recursion, allow_ebnf, validate_references)
}

