# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseBNF <- function(input, strict_validation = TRUE, strict_mode = FALSE) {
    .Call(`_bnfparser_parseBNF`, input, strict_validation, strict_mode)
}

